module.exports={
    configureWebpack:{
        resole:{
            alias:{
                'assets':'@/assets',
                'common':'@/common',
                'components':'@/components',
                'network':'@/network',
            }
        }
    }
}